// <auto-generated />
using System;
using EpisodeApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EpisodeApp.Data.Migrations
{
    [DbContext(typeof(EpisodesContext))]
    partial class EpisodesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Episode", b =>
                {
                    b.Property<int>("EpisodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("GuestName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EpisodeId");

                    b.ToTable("Episode");

                    b.HasData(
                        new
                        {
                            EpisodeId = 1,
                            Date = new DateTime(2021, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestName = "Claire Novotny",
                            Title = "All about Open Source and .NET",
                            URL = "https://www.youtube.com/watch?v=flj9MHrOU0k"
                        },
                        new
                        {
                            EpisodeId = 2,
                            Date = new DateTime(2020, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestName = "Layla Porter",
                            Title = "Migrating ASP NET Identity to Azure AD B2C",
                            URL = "https://www.youtube.com/watch?v=lQlev9oRtXQ"
                        },
                        new
                        {
                            EpisodeId = 3,
                            Date = new DateTime(2021, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestName = "Joonas Westlin",
                            Title = "Identity Crisis sidecar: Legacy software. Let's learn foxpro!",
                            URL = "https://www.youtube.com/watch?v=xCkS0e2voE8"
                        },
                        new
                        {
                            EpisodeId = 4,
                            Date = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestName = "",
                            Title = "Identity Crisis - Getting started with Identity",
                            URL = "https://www.youtube.com/watch?v=bniAj9q4s7c"
                        },
                        new
                        {
                            EpisodeId = 5,
                            Date = new DateTime(2021, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GuestName = "Sean Whitesell",
                            Title = "Secure DevOps with Pulumi and Azure AD",
                            URL = "https://www.youtube.com/watch?v=DdTJNAXZ1k4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
